# Generated by Django 3.1.2 on 2020-11-23 23:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kurs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Имя курс')),
            ],
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('sirname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('timeOfKurs', models.IntegerField(null=True, verbose_name='Время урок')),
                ('dayOfDate', models.CharField(max_length=20, verbose_name='Дни в недели')),
                ('telParents', models.IntegerField(null=True, verbose_name='Телефон родители')),
                ('telMe', models.IntegerField(verbose_name='Мой телефон')),
                ('group', models.IntegerField(verbose_name='Группа')),
                ('kurs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sms.kurs')),
            ],
        ),
        migrations.CreateModel(
            name='SaveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(verbose_name='Время')),
                ('typeOfMessage', models.TextField(verbose_name='Сообщение')),
                ('id_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='sms.students')),
            ],
        ),
    ]
